#!/bin/sh

ROLE_ARN=$1
SESSION_NAME=$2
COMMAND="${@:3}"

if [ -z "$ROLE_ARN" ] || [ -z "$SESSION_NAME" ] || [ -z "$COMMAND" ]; then
  echo "Usage: $0 <role-arn> <session-name> <command>"
  exit 1
fi

ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn "$ROLE_ARN" --role-session-name "$SESSION_NAME")

if [ $? -ne 0 ]; then
  echo "Failed to assume role: $ROLE_ARN"
  exit 1
fi

export AWS_ACCESS_KEY_ID=$(echo "$ASSUME_ROLE_OUTPUT" | jq -r '.Credentials.AccessKeyId')
export AWS_SECRET_ACCESS_KEY=$(echo "$ASSUME_ROLE_OUTPUT" | jq -r '.Credentials.SecretAccessKey')
export AWS_SESSION_TOKEN=$(echo "$ASSUME_ROLE_OUTPUT" | jq -r '.Credentials.SessionToken')

echo "Running command: $COMMAND"
eval "$COMMAND"

EXIT_CODE=$?
unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
exit $EXIT_CODE

